title:         edongashi
tagline:       'Shënimet e ushtrimeve'
description:   'Shënimet e ushtrimeve për Inxhinieri Kompjuterike'
url:           https://edongashi.github.io
analytics:     G-B7RYXP02L4
lang:          sq
paginate_path: "/blog/page:num/"
paginate:      3
